version: '3'

services:
  loadbalancer:
    build:
      context: ./
      dockerfile: LoadBalancer.Dockerfile
    ports:
      - 8080:80
    environment:
      LoadBalancerListenUrl:  http://*:80/
      MessageBrokerConnectionString:  Host=messagebroker;Username=guest;Password=guest
      RedisHost:  redis
    depends_on:
      - messagebroker
      - redis
  web_md:
    build:
      context: ./
      dockerfile: WebApplication.Dockerfile
    environment:
      ConnectionStrings:Default:  Server=sql_md;Database=movie;User ID=postgres;Password=3x4mpl3
      ConnectionStrings:MessageBroker:  Host=messagebroker;Username=guest;Password=guest
    depends_on:
      - sql_md
      - messagebroker
  sql_md:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD:  3x4mpl3

  web_us:
    build:
      context: ./
      dockerfile: WebApplication.Dockerfile
    environment:
      ConnectionStrings:Default:  Server=sql_us;Database=movie;User ID=postgres;Password=3xfdsapl3
      ConnectionStrings:MessageBroker:  Host=messagebroker;Username=guest;Password=guest
    depends_on:
      - sql_us
      - messagebroker
  sql_us:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD:  3xfdsapl3

  redis:
    image:  redis
  messagebroker:
    image: "rabbitmq:3-management"
    hostname: "messagebroker"
    ports:
      - 15672:15672
